name: ${PROJECT_NAME:-tempo}

services:
  # Frontend React (Vite)
  frontend:
    build:
      context: .
      # Asumimos que el Dockerfile estará en la raíz del proyecto
      dockerfile: ./docker/frontend/Dockerfile 
    image: ${PROJECT_NAME:-tempo}-frontend-image
    container_name: ${PROJECT_NAME:-tempo}-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    ports:
      - "${PORT_WEB:-5173}:5173" # Exponemos el puerto por defecto de Vite
    volumes:
      # Mapeamos la raíz de tu proyecto local a la carpeta /app del contenedor
      - ./:/app
      # Protegemos la carpeta node_modules del contenedor para que tu entorno local no la sobreescriba
      - /app/node_modules 
    healthcheck:
      test: ["CMD-SHELL", "npm run dev -- --host 0.0.0.0"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 15s
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
  public_network:
    external: true